      version: '3'
      services:
              web:
                      image: flask
                      build: .
                      env_file:
                              - .env
                      ports:
                              - "8421:8421"
                      volumes:
                              - ./instance:/instance
                              - ./events.db:/app/events.db      # ← ADD THIS
                              - ./static/flyers:/app/static/flyers  # ← also add this for flyer uploads
                      restart: unless-stopped
